### PR TITLE
add multiple validator validate method with format

### PR DESCRIPTION
**Pull request by suguangwen**
add multiple validator validate method with format {{$$validator_name}}

### CODE REVIEW

**Comment by kazupon** [comment]
Thank you for your PR!

It seems that you define the validate method for multiple only.
I hope that implementation of  multiple validate method.

**Comment by suguangwen** [comment]
I'm sorry，Submit code missing part of yesterday。

**Comment by MSidabras** [comment]
@kazupon hi, is this implemented in master branch? I need this functionality

**Comment by kazupon** [comment]
released v3.0.0-alpha.1
https://github.com/vuejs/vue-validator/releases/tag/v3.0.0-alpha.1

We can use the 'valdity' component.

**Pull request closed without merging**
